### ISSUE TITLE
After logging in, user should be redirected to Data Browser page

### ISSUE THREAD

**Issue by coverbeck** [BD2KGenomics/dcc-dashboard#39]
Currently, after logging in, you always go to the home page.

We could remember what page you were on, but it’s easier to just redirect the user to the data browser page.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-3)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-3

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Optionally, since we really only have one page, we could just always redirect to the data browser.
