### ISSUE TITLE
Improve Token Handling

### ISSUE THREAD

**Issue by coverbeck** [BD2KGenomics/dcc-dashboard#42]
1. We currently request a new access token every time an access token is used in an API call; we could store the access token expiration and refresh more intelligently.
2. We currently assume the refresh token never expires. I thought they didn't, although they can be revoked, so even if they didn't, we still need to handle that case briefly.

With DataBiosphere/cgp-boardwalk#11, the need to make API calls with Google tokens may go away on the one side, but on the other side, calls to the indexer may start requiring tokens may bring the need back in.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-11)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-11

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

Not urgent, but needed for production

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

This is going to be rendered moot by BOARD-5 -- we will no longer be making API calls to FC, so we will not need to request new access tokens. Given that upcoming change, I'm going to close this one.
