### ISSUE TITLE
Status page on dashboard

### ISSUE THREAD

**Issue by natanlao** [BD2KGenomics/dcc-dashboard#43]
Issue moved |
---|
This issue was moved from [BD2KGenomics/dcc-ops#61](https://github.com/BD2KGenomics/dcc-ops/issues/61). |

To help with understanding if a fresh install (or running production version) of dcc-ops is working we need to have a status page on our website.  For example http://<domain>/status.html.

This would give a nice, simple indicator showing that all the components are reachable and working as expected.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-12)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-12

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

This is a good idea, but going to reject as this undergoing major rework with Gatsby changes.
