### ISSUE TITLE
Remove code that supports export to FireCloud using bearer token

### ISSUE THREAD

**Issue by mjkrause** [BD2KGenomics/dcc-dashboard#79]
Remove the two methods `export_to_firecloud` and `proxy_firecloud`.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-32)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-32

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

Resolved in TLP‌-560
