### ISSUE TITLE
Once Google token expires, token is only refreshed on log out

### ISSUE THREAD

**Issue by cricketsloan** [BD2KGenomics/dcc-dashboard#91]
Once a token is created, for a session in dashboard the token will expire after two hours. At this point the user is prompted to log in again with Google. Clicking this link will not re-log / refresh their token, but rather just direct them back to the same page. The user has to manually click log out, then log back in to get things to work.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DASH-37)
┆Project Name: CGP-Dashboard
┆Issue Number: DASH-37

**Comment by coverbeck** [comment]
I believe the access token expires after one hour. I had fixed a bug, #75  (I think) where the access token was not getting refreshed correctly after one hour.

Either #75 was not fixed correctly, or, perhaps, the first refresh works, but the second one does not -- that might explain why it takes two hours to see this issue. Need to investigate.

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

What behavior do we want? As long as user input is detected in the last x min the token should refresh automatically. Or once the token is expired the user should be able to click the login link and get logged in again?

**Comment by coverbeck** [comment]
The access token should automatically be refreshed, transparently to the user, as long as the refresh token has not expired and the user has not logged out. The refresh token is good for a month I believe.

It has been discussed as a feature to log out the user after a period of inactivity, but that is another feature and  separate from this -- if the user was continuously active for 2+ hours, they would run into this bug.

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

[~brennan], the fix [~coverbec] mentions is from Oct 3, so quite recent. Do we know that this has not fixed this current story? If not, how did you find out? In other words, what would be a good approach / strategy to reproduce the error of access token expiration?

**Comment by jessebrennan** [comment]
It seems like the previous fix was insufficient. To reproduce, just log into staging (or possibly dev, though I'm not positive), wait like an hour, then click log in. You will be redirected to the landing page with your name indicating that you are logged in, but clicking on "Data Browser" starts you back in the cycle.

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

Hi [~brennan] and [~coverbec], before I embark on that, just want to make sure that I fully understand the problem. 

Last night I left several instances open after I had logged. This morning I made the following observation: if a user logs in to the dev instance of the Commons Boardwalk (mind that this happened last night), and is inactive for more than 1 h, then clicks the link "Data Browser", the Login page is shown, indicating that user isn't logged in anymore.

If the user then does not log in, but instead clicks on "Home",the log-in link (the one to the very right) shows the user as logged in (although s/he isn't). What we would want instead is that it shows that the user isn't logged in.

If the user instead is on the Data Browser page (after having been logged in, one hour has passed, and after browser is refreshed it shows "Login..." page) and clicks on the Login link, but does not log in, then goes back to "Home", it shows correctly that user isn't logged in.

**Comment by coverbeck** [comment]
The desired behavior is that the user stay logged in. The problem seems to be that a new access token is not generated correctly; I think that mainly needs to be focused on, and the rest is just fallout from the access token not being refreshed correctly (apparently).
